services:
  consul1:
    command: agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0
    hostname: consul1
    image: consul:latest
    ports:
    - 8400:8400
    - 8500:8500
    - 8600:8600
  consul2:
    command: agent -server -retry-join consul1 -disable-host-node-id
    depends_on:
    - consul1
    expose:
    - "8400"
    - "8500"
    - "8600"
    hostname: consul2
    image: consul:latest
  consul3:
    command: agent -server -retry-join consul1 -disable-host-node-id
    depends_on:
    - consul1
    expose:
    - "8400"
    - "8500"
    - "8600"
    hostname: consul3
    image: consul:latest
  vtctld:
    command:
    - sh
    - -c
    - ' $$VTROOT/bin/vtctld $TOPOLOGY_FLAGS -cell $CELL -web_dir $$VTTOP/web/vtctld
      -web_dir2 $$VTTOP/web/vtctld2/app -workflow_manager_init -workflow_manager_use_election
      -service_map ''grpc-vtctl'' -backup_storage_implementation file -file_backup_storage_root
      $$VTDATAROOT/backups -logtostderr=true -port $WEB_PORT -grpc_port $GRPC_PORT
      -pid_file $$VTDATAROOT/tmp/vtctld.pid '
    depends_on:
    - consul1
    - consul2
    - consul3
    image: vitess/base
    ports:
    - 15000:$WEB_PORT
    - $GRPC_PORT
    volumes:
    - .:/script
  vtgate:
    command:
    - sh
    - -c
    - '/script/run-forever.sh $$VTROOT/bin/vtgate /script/vtbins/vtgate -- $TOPOLOGY_FLAGS
      -logtostderr=true -port $WEB_PORT -grpc_port $GRPC_PORT -mysql_server_port $MYSQL_PORT
      -mysql_auth_server_impl none -cell $CELL -cells_to_watch $CELL -tablet_types_to_wait
      MASTER,REPLICA,RDONLY -gateway_implementation discoverygateway -service_map
      ''grpc-vtgateservice'' -pid_file $$VTDATAROOT/tmp/vtgate.pid -normalize_queries=true '
    depends_on:
    - vtctld
    image: vitess/base
    ports:
    - 15099:$WEB_PORT
    - $GRPC_PORT
    - 15306:$MYSQL_PORT
    security_opt:
    - seccomp:unconfined
    volumes:
    - .:/script
  vtwork:
    command:
    - sh
    - -c
    - '$$VTROOT/bin/vtworker $TOPOLOGY_FLAGS -cell $CELL -logtostderr=true -service_map
      ''grpc-vtworker'' -port $WEB_PORT -grpc_port $GRPC_PORT -use_v3_resharding_mode=true
      -pid_file $$VTDATAROOT/tmp/vtwork.pid '
    depends_on:
    - vtctld
    image: vitess/base
    ports:
    - 15100:$WEB_PORT
    - $GRPC_PORT
version: "3"

